Repository RoutinelyOrganization/routinely-web, pull requests merged in 2023-07, with the labels that each got.

#5 chore: initial project setup with React, Vite, and TypeScript configured Eslint and Prettier
  .eslintrc.cjs
  .eslintrc.json
  .gitignore
  .prettierrc
  LICENSE
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: enhancement

#7 Feat/home page
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/GlobalStyles.tsx
  src/assets/imagens/homePageImage.svg
  src/components/Button/ButtonStyles.tsx
  src/components/Logo/index.tsx
  src/main.tsx
  src/pages/HomePage/HomePageStyles.tsx
  src/pages/HomePage/index.tsx
  src/routes/routes.tsx
Labels: enhancement

#8 chore: added license
  LICENSE
Labels: documentation

#12 fix: text alignment
  src/pages/HomePage/HomePageStyles.tsx
Labels: bug
